version: '3'
services:
  search-guard-tlstool:
    build:
      context: search-guard-tlstool
    volumes:
      - ./certificates:/tools/certificates

  opensearch-node1:
    image: opensearchproject/opensearch:2.1.0
    container_name: opensearch-node1
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 8G
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms4096m -Xmx4096m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - network.host=0.0.0.0 # required if not using the demo security configuration
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ./certificates/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      - ./certificates/node.pem:/usr/share/opensearch/config/node.pem
      - ./certificates/node.key:/usr/share/opensearch/config/node-key.pem
      - ./certificates/admin.pem:/usr/share/opensearch/config/admin.pem
      - ./certificates/admin.key:/usr/share/opensearch/config/admin-key.pem
      - ./conf/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./conf/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
      - ./conf/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml
      - ./conf/tenants.yml:/usr/share/opensearch/config/opensearch-security/tenants.yml
      - ./conf/roles.yml:/usr/share/opensearch/config/opensearch-security/roles.yml
      - ./conf/action_groups.yml:/usr/share/opensearch/config/opensearch-security/action_groups.yml
      - ./conf/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
    depends_on:
      - search-guard-tlstool

  opensearch-node2:
    image: opensearchproject/opensearch:2.1.0
    container_name: opensearch-node2
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 8G
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
      - ./certificates/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      - ./certificates/node.pem:/usr/share/opensearch/config/node.pem
      - ./certificates/node.key:/usr/share/opensearch/config/node-key.pem
      - ./certificates/admin.pem:/usr/share/opensearch/config/admin.pem
      - ./certificates/admin.key:/usr/share/opensearch/config/admin-key.pem
      - ./conf/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./conf/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
      - ./conf/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml
      - ./conf/tenants.yml:/usr/share/opensearch/config/opensearch-security/tenants.yml
      - ./conf/roles.yml:/usr/share/opensearch/config/opensearch-security/roles.yml
      - ./conf/action_groups.yml:/usr/share/opensearch/config/opensearch-security/action_groups.yml
      - ./conf/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
    networks:
      - opensearch-net
    depends_on:
      - search-guard-tlstool

  opensearch-node3:
    image: opensearchproject/opensearch:2.1.0
    container_name: opensearch-node3
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 8G
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node3
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data3:/usr/share/opensearch/data
      - ./certificates/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      - ./certificates/node.pem:/usr/share/opensearch/config/node.pem
      - ./certificates/node.key:/usr/share/opensearch/config/node-key.pem
      - ./certificates/admin.pem:/usr/share/opensearch/config/admin.pem
      - ./certificates/admin.key:/usr/share/opensearch/config/admin-key.pem
      - ./conf/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./conf/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
      - ./conf/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml
      - ./conf/tenants.yml:/usr/share/opensearch/config/opensearch-security/tenants.yml
      - ./conf/roles.yml:/usr/share/opensearch/config/opensearch-security/roles.yml
      - ./conf/action_groups.yml:/usr/share/opensearch/config/opensearch-security/action_groups.yml
      - ./conf/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
    networks:
      - opensearch-net
    depends_on:
      - search-guard-tlstool

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.1.0
    container_name: opensearch-dashboards
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 8G
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200","https://opensearch-node3:9200"]' # must be a string with no spaces when specified as an environment variable
    volumes:
      - ./conf/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node2
      - opensearch-node1
      - opensearch-node3

  log-pilot-docker:
    build:
      context: log-pilot
      dockerfile: Dockerfile.docker

  log-pilot-cotainerd:
    build:
      context: log-pilot
      dockerfile: Dockerfile.containerd

  elastalert:
    image: jertel/elastalert2:2.6.0
    container_name: elastalert
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 4G
    volumes:
      - ./elastalert/config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./elastalert/rules:/opt/elastalert/rules
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/elk/data1
  opensearch-data2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/elk/data2
  opensearch-data3:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/elk/data3

networks:
  opensearch-net: